"""
Unit tests for backend.services.library_scan_service.

Fixtures are generated by tests/fixtures/create_audio_fixtures.py and live in
tests/fixtures/audio/.  Individual tests skip gracefully if a fixture file is
missing.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from mutagen._util import MutagenError

from backend.domain.models import LibraryFile, LibraryQuarantine
from backend.services.library_scan_service import (
    _sanitise_tag_value,
    extract_tags,
    scan_directory,
)

# ---------------------------------------------------------------------------
# Fixture paths
# ---------------------------------------------------------------------------

AUDIO_DIR = Path(__file__).parent.parent / "fixtures" / "audio"

WELL_TAGGED = AUDIO_DIR / "well_tagged.mp3"
PARTIAL_TAGS = AUDIO_DIR / "partial_tags.mp3"
MINIMAL_OGG = AUDIO_DIR / "minimal_tags.ogg"
NO_TAGS_WAV = AUDIO_DIR / "no_tags.wav"
CORRUPT_MP3 = AUDIO_DIR / "corrupt.mp3"


def _require(path: Path) -> Path:
    """Skip the test if the fixture file does not exist."""
    if not path.exists():
        pytest.skip(f"Fixture not found: {path}")
    return path


# ---------------------------------------------------------------------------
# well_tagged.mp3  — Tier 1: all MusicBrainz IDs
# ---------------------------------------------------------------------------


class TestWellTaggedMp3:
    def test_recording_mbid(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.recording_mbid == "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"

    def test_artist_mbid(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.artist_mbid == "11111111-2222-3333-4444-555555555555"

    def test_album_artist_mbid(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.album_artist_mbid == "66666666-7777-8888-9999-aaaaaaaaaaaa"

    def test_release_mbid(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.release_mbid == "bbbbbbbb-cccc-dddd-eeee-ffffffffffff"

    def test_track_title(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.track_title == "Test Track One"

    def test_release_title(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.release_title == "Test Album"

    def test_track_number_parsed_from_slash_notation(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.track_number == 3

    def test_disc_number_parsed_from_slash_notation(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.disc_number == 1

    def test_format_is_mp3(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.format == "mp3"

    def test_release_type_album(self) -> None:
        from backend.domain.enums import ReleaseType
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.release_type == ReleaseType.ALBUM

    def test_release_status_official(self) -> None:
        from backend.domain.enums import ReleaseStatus
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.release_status == ReleaseStatus.OFFICIAL

    def test_duration_ms_positive(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.duration_ms is not None
        assert lf.duration_ms > 0

    def test_file_hash_is_64_char_hex(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert re.fullmatch(r"[0-9a-f]{64}", lf.file_hash)

    def test_raw_metadata_present(self) -> None:
        lf = extract_tags(_require(WELL_TAGGED))
        assert lf.raw_metadata is not None
        assert len(lf.raw_metadata) > 0


# ---------------------------------------------------------------------------
# partial_tags.mp3 — Tier 2: title/artist, no MBIDs
# ---------------------------------------------------------------------------


class TestPartialTagsMp3:
    def test_track_title_present(self) -> None:
        lf = extract_tags(_require(PARTIAL_TAGS))
        assert lf.track_title == "Partial Track"

    def test_no_recording_mbid(self) -> None:
        lf = extract_tags(_require(PARTIAL_TAGS))
        assert lf.recording_mbid is None

    def test_no_artist_mbid(self) -> None:
        lf = extract_tags(_require(PARTIAL_TAGS))
        assert lf.artist_mbid is None

    def test_no_release_mbid(self) -> None:
        lf = extract_tags(_require(PARTIAL_TAGS))
        assert lf.release_mbid is None

    def test_track_number_without_slash(self) -> None:
        lf = extract_tags(_require(PARTIAL_TAGS))
        assert lf.track_number == 5

    def test_format_is_mp3(self) -> None:
        lf = extract_tags(_require(PARTIAL_TAGS))
        assert lf.format == "mp3"

    def test_file_hash_is_64_char_hex(self) -> None:
        lf = extract_tags(_require(PARTIAL_TAGS))
        assert re.fullmatch(r"[0-9a-f]{64}", lf.file_hash)


# ---------------------------------------------------------------------------
# minimal_tags.ogg — Tier 3: basic Vorbis tags
# ---------------------------------------------------------------------------


class TestMinimalOgg:
    def test_track_title_present(self) -> None:
        lf = extract_tags(_require(MINIMAL_OGG))
        assert lf.track_title == "Minimal Track"

    def test_no_mbids(self) -> None:
        lf = extract_tags(_require(MINIMAL_OGG))
        assert lf.recording_mbid is None
        assert lf.artist_mbid is None
        assert lf.release_mbid is None

    def test_format_is_ogg(self) -> None:
        lf = extract_tags(_require(MINIMAL_OGG))
        assert lf.format == "ogg"

    def test_duration_ms_positive(self) -> None:
        lf = extract_tags(_require(MINIMAL_OGG))
        assert lf.duration_ms is not None
        assert lf.duration_ms > 0

    def test_file_hash_is_64_char_hex(self) -> None:
        lf = extract_tags(_require(MINIMAL_OGG))
        assert re.fullmatch(r"[0-9a-f]{64}", lf.file_hash)


# ---------------------------------------------------------------------------
# no_tags.wav — Tier 3: untagged WAV
# ---------------------------------------------------------------------------


class TestNoTagsWav:
    def test_format_is_wav(self) -> None:
        lf = extract_tags(_require(NO_TAGS_WAV))
        assert lf.format == "wav"

    def test_no_track_title(self) -> None:
        lf = extract_tags(_require(NO_TAGS_WAV))
        assert lf.track_title is None

    def test_no_mbids(self) -> None:
        lf = extract_tags(_require(NO_TAGS_WAV))
        assert lf.recording_mbid is None
        assert lf.artist_mbid is None

    def test_duration_ms_positive(self) -> None:
        lf = extract_tags(_require(NO_TAGS_WAV))
        assert lf.duration_ms is not None
        assert lf.duration_ms > 0

    def test_file_hash_is_64_char_hex(self) -> None:
        lf = extract_tags(_require(NO_TAGS_WAV))
        assert re.fullmatch(r"[0-9a-f]{64}", lf.file_hash)


# ---------------------------------------------------------------------------
# corrupt.mp3 — should raise on extract_tags
# ---------------------------------------------------------------------------


class TestCorruptMp3:
    def test_raises_mutagen_error(self) -> None:
        _require(CORRUPT_MP3)
        with pytest.raises(MutagenError):
            extract_tags(CORRUPT_MP3)


# ---------------------------------------------------------------------------
# scan_directory
# ---------------------------------------------------------------------------


class TestScanDirectory:
    def test_returns_four_files_and_one_quarantine(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        files, quarantine = scan_directory(AUDIO_DIR)
        assert len(files) == 4
        assert len(quarantine) == 1

    def test_quarantine_contains_corrupt_file(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        _, quarantine = scan_directory(AUDIO_DIR)
        quarantine_names = [Path(q.file_path).name for q in quarantine]
        assert "corrupt.mp3" in quarantine_names

    def test_quarantine_error_message_not_empty(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        _, quarantine = scan_directory(AUDIO_DIR)
        for q in quarantine:
            assert q.error_message

    def test_skips_non_audio_files(self, tmp_path: Path) -> None:
        # Create a small audio dir with one valid WAV and one .txt file
        wav_src = _require(NO_TAGS_WAV)
        import shutil
        shutil.copy(wav_src, tmp_path / "valid.wav")
        (tmp_path / "readme.txt").write_text("not audio")
        (tmp_path / "image.jpg").write_bytes(b"\xff\xd8\xff" + b"\x00" * 20)

        files, quarantine = scan_directory(tmp_path)
        assert len(files) == 1
        assert len(quarantine) == 0
        assert files[0].format == "wav"

    def test_all_files_have_valid_hashes(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        files, _ = scan_directory(AUDIO_DIR)
        for lf in files:
            assert re.fullmatch(r"[0-9a-f]{64}", lf.file_hash), (
                f"Invalid hash for {lf.file_path}: {lf.file_hash!r}"
            )

    def test_all_files_have_uuids(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        from uuid import UUID
        files, quarantine = scan_directory(AUDIO_DIR)
        all_ids = [lf.id for lf in files] + [q.id for q in quarantine]
        for uid in all_ids:
            assert isinstance(uid, UUID)

    def test_file_paths_are_absolute_strings(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        files, quarantine = scan_directory(AUDIO_DIR)
        for lf in files:
            assert Path(lf.file_path).is_absolute()
        for q in quarantine:
            assert Path(q.file_path).is_absolute()

    def test_on_file_callback_called_per_extracted_file(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        received: list[LibraryFile] = []
        files, _ = scan_directory(AUDIO_DIR, on_file=lambda lf: received.append(lf))
        assert len(received) == len(files)
        assert {lf.file_path for lf in received} == {lf.file_path for lf in files}

    def test_on_quarantine_callback_called_per_quarantined_file(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        received: list[LibraryQuarantine] = []
        _, quarantine = scan_directory(
            AUDIO_DIR, on_quarantine=lambda q: received.append(q)
        )
        assert len(received) == len(quarantine)


# ---------------------------------------------------------------------------
# _sanitise_tag_value — null byte / control char stripping
# ---------------------------------------------------------------------------


class TestSanitiseTagValue:
    def test_strips_null_bytes(self) -> None:
        assert _sanitise_tag_value("Rock\x00") == "Rock"

    def test_strips_embedded_null_bytes(self) -> None:
        assert _sanitise_tag_value("Ro\x00ck\x00") == "Rock"

    def test_clean_string_unchanged(self) -> None:
        assert _sanitise_tag_value("Jazz") == "Jazz"

    def test_empty_string(self) -> None:
        assert _sanitise_tag_value("") == ""

    def test_non_string_converted(self) -> None:
        assert _sanitise_tag_value(42) == "42"

    def test_object_with_failing_str_uses_repr(self) -> None:
        class BadStr:
            def __str__(self) -> str:
                raise ValueError("nope")

            def __repr__(self) -> str:
                return "<BadStr>"

        assert _sanitise_tag_value(BadStr()) == "<BadStr>"
