"""
Unit tests for backend.services.library_scan_service.

Fixtures are generated by tests/fixtures/create_audio_fixtures.py and live in
tests/fixtures/audio/.  Individual tests skip gracefully if a fixture file is
missing.
"""

from __future__ import annotations

import dataclasses
import os
from pathlib import Path
from unittest.mock import MagicMock, patch

import mutagen
import pytest
from mutagen._util import MutagenError

from backend.domain.library import LibraryFile, LibraryQuarantine
from backend.services.library_scan_service import (
    DiskStat,
    _extract_audio_stream_metrics,
    _extract_first_tag_value,
    _parse_slash_int,
    _sanitise_tag_value,
    _to_release_status,
    _to_release_type,
    read_tags,
    scan_directory,
)
from tests.fixtures.audio_builders import tag_flac, write_flac

# ---------------------------------------------------------------------------
# Fixture paths
# ---------------------------------------------------------------------------

AUDIO_DIR = Path(__file__).parent.parent / "fixtures" / "audio"

WELL_TAGGED = AUDIO_DIR / "well_tagged.mp3"
PARTIAL_TAGS = AUDIO_DIR / "partial_tags.mp3"
MINIMAL_OGG = AUDIO_DIR / "minimal_tags.ogg"
NO_TAGS_WAV = AUDIO_DIR / "no_tags.wav"
CORRUPT_MP3 = AUDIO_DIR / "corrupt.mp3"


def _require(path: Path) -> Path:
    """Skip the test if the fixture file does not exist."""
    if not path.exists():
        pytest.skip(f"Fixture not found: {path}")
    return path


# ---------------------------------------------------------------------------
# well_tagged.mp3  — Tier 1: all MusicBrainz IDs
# ---------------------------------------------------------------------------


class TestWellTaggedMp3:
    def test_recording_mbid(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.recording_mbid == "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"

    def test_artist_mbid(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.artist_mbid == "11111111-2222-3333-4444-555555555555"

    def test_album_artist_mbid(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.album_artist_mbid == "66666666-7777-8888-9999-aaaaaaaaaaaa"

    def test_release_mbid(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.release_mbid == "bbbbbbbb-cccc-dddd-eeee-ffffffffffff"

    def test_track_title(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.track_title == "Test Track One"

    def test_release_title(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.release_title == "Test Album"

    def test_track_number_parsed_from_slash_notation(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.track_number == 3

    def test_disc_number_parsed_from_slash_notation(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.disc_number == 1

    def test_format_is_mp3(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.format == "mp3"

    def test_release_type_album(self) -> None:
        from backend.domain.enums import ReleaseType

        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.release_type == ReleaseType.ALBUM

    def test_release_status_official(self) -> None:
        from backend.domain.enums import ReleaseStatus

        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.release_status == ReleaseStatus.OFFICIAL

    def test_duration_ms_positive(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.duration_ms is not None
        assert lf.audio.duration_ms > 0

    def test_raw_metadata_present(self) -> None:
        lf = read_tags(_require(WELL_TAGGED))
        assert lf.audio.raw_metadata is not None
        assert len(lf.audio.raw_metadata) > 0

    def test_file_stat_captured(self) -> None:
        """Size + mtime are what lets the next scan skip this file unread."""
        path = _require(WELL_TAGGED)
        lf = read_tags(path)
        st = path.stat()
        assert lf.file_size == st.st_size
        assert lf.file_mtime_ns == st.st_mtime_ns


def test_a_retag_during_the_tag_read_leaves_a_stale_stored_stat(tmp_path: Path) -> None:
    """The stat is taken before the read, so the next scan sees the rewrite and re-reads."""
    path = write_flac(tmp_path / "a.flac", [(300, -300)])
    tag_flac(path, {"title": "Kiss"})
    before = path.stat()
    real_parse = mutagen.File  # type: ignore[attr-defined]

    def parse_then_retag(*args: object, **kwargs: object) -> object:
        audio = real_parse(*args, **kwargs)
        tag_flac(path, {"title": "Kiss (Extended Version)"})
        os.utime(path, ns=(before.st_atime_ns, before.st_mtime_ns + 1_000_000_000))
        return audio

    with patch("mutagen.File", side_effect=parse_then_retag):
        lf = read_tags(path)

    assert lf.audio.track_title == "Kiss"
    assert (lf.file_size, lf.file_mtime_ns) == (before.st_size, before.st_mtime_ns)


# ---------------------------------------------------------------------------
# partial_tags.mp3 — Tier 2: title/artist, no MBIDs
# ---------------------------------------------------------------------------


class TestPartialTagsMp3:
    def test_track_title_present(self) -> None:
        lf = read_tags(_require(PARTIAL_TAGS))
        assert lf.audio.track_title == "Partial Track"

    def test_no_recording_mbid(self) -> None:
        lf = read_tags(_require(PARTIAL_TAGS))
        assert lf.audio.recording_mbid is None

    def test_no_artist_mbid(self) -> None:
        lf = read_tags(_require(PARTIAL_TAGS))
        assert lf.audio.artist_mbid is None

    def test_no_release_mbid(self) -> None:
        lf = read_tags(_require(PARTIAL_TAGS))
        assert lf.audio.release_mbid is None

    def test_track_number_without_slash(self) -> None:
        lf = read_tags(_require(PARTIAL_TAGS))
        assert lf.audio.track_number == 5

    def test_format_is_mp3(self) -> None:
        lf = read_tags(_require(PARTIAL_TAGS))
        assert lf.format == "mp3"


# ---------------------------------------------------------------------------
# minimal_tags.ogg — Tier 3: basic Vorbis tags
# ---------------------------------------------------------------------------


class TestMinimalOgg:
    def test_track_title_present(self) -> None:
        lf = read_tags(_require(MINIMAL_OGG))
        assert lf.audio.track_title == "Minimal Track"

    def test_no_mbids(self) -> None:
        lf = read_tags(_require(MINIMAL_OGG))
        assert lf.audio.recording_mbid is None
        assert lf.audio.artist_mbid is None
        assert lf.audio.release_mbid is None

    def test_format_is_ogg(self) -> None:
        lf = read_tags(_require(MINIMAL_OGG))
        assert lf.format == "ogg"

    def test_duration_ms_positive(self) -> None:
        lf = read_tags(_require(MINIMAL_OGG))
        assert lf.audio.duration_ms is not None
        assert lf.audio.duration_ms > 0


# ---------------------------------------------------------------------------
# no_tags.wav — Tier 3: untagged WAV
# ---------------------------------------------------------------------------


class TestNoTagsWav:
    def test_format_is_wav(self) -> None:
        lf = read_tags(_require(NO_TAGS_WAV))
        assert lf.format == "wav"

    def test_no_track_title(self) -> None:
        lf = read_tags(_require(NO_TAGS_WAV))
        assert lf.audio.track_title is None

    def test_no_mbids(self) -> None:
        lf = read_tags(_require(NO_TAGS_WAV))
        assert lf.audio.recording_mbid is None
        assert lf.audio.artist_mbid is None

    def test_duration_ms_positive(self) -> None:
        lf = read_tags(_require(NO_TAGS_WAV))
        assert lf.audio.duration_ms is not None
        assert lf.audio.duration_ms > 0


# ---------------------------------------------------------------------------
# corrupt.mp3 — should raise on read_tags
# ---------------------------------------------------------------------------


class TestCorruptMp3:
    def test_raises_mutagen_error(self) -> None:
        _require(CORRUPT_MP3)
        with pytest.raises(MutagenError):
            read_tags(CORRUPT_MP3)


# ---------------------------------------------------------------------------
# scan_directory
# ---------------------------------------------------------------------------


class TestScanDirectory:
    def test_returns_four_files_and_one_quarantine(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        files, quarantine = scan_directory(AUDIO_DIR)
        assert len(files) == 4
        assert len(quarantine) == 1

    def test_quarantine_contains_corrupt_file(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        _, quarantine = scan_directory(AUDIO_DIR)
        quarantine_names = [Path(q.file_path).name for q in quarantine]
        assert "corrupt.mp3" in quarantine_names

    def test_quarantine_error_message_not_empty(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        _, quarantine = scan_directory(AUDIO_DIR)
        for q in quarantine:
            assert q.error_message

    def test_skips_non_audio_files(self, tmp_path: Path) -> None:
        # Create a small audio dir with one valid WAV and one .txt file
        wav_src = _require(NO_TAGS_WAV)
        import shutil

        shutil.copy(wav_src, tmp_path / "valid.wav")
        (tmp_path / "readme.txt").write_text("not audio")
        (tmp_path / "image.jpg").write_bytes(b"\xff\xd8\xff" + b"\x00" * 20)

        files, quarantine = scan_directory(tmp_path)
        assert len(files) == 1
        assert len(quarantine) == 0
        assert files[0].format == "wav"

    def test_all_files_have_uuids(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        from uuid import UUID

        files, quarantine = scan_directory(AUDIO_DIR)
        all_ids = [lf.id for lf in files] + [q.id for q in quarantine]
        for uid in all_ids:
            assert isinstance(uid, UUID)

    def test_file_paths_are_absolute_strings(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        files, quarantine = scan_directory(AUDIO_DIR)
        for lf in files:
            assert Path(lf.file_path).is_absolute()
        for q in quarantine:
            assert Path(q.file_path).is_absolute()

    def test_on_file_callback_called_per_extracted_file(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        received: list[LibraryFile] = []
        files, _ = scan_directory(AUDIO_DIR, on_file=lambda lf: received.append(lf))
        assert len(received) == len(files)
        assert {lf.file_path for lf in received} == {lf.file_path for lf in files}

    def test_on_quarantine_callback_called_per_quarantined_file(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        received: list[LibraryQuarantine] = []
        _, quarantine = scan_directory(AUDIO_DIR, on_quarantine=lambda q: received.append(q))
        assert len(received) == len(quarantine)


# ---------------------------------------------------------------------------
# _sanitise_tag_value — null byte / control char stripping
# ---------------------------------------------------------------------------


class TestSanitiseTagValue:
    def test_strips_null_bytes(self) -> None:
        assert _sanitise_tag_value("Rock\x00") == "Rock"

    def test_strips_embedded_null_bytes(self) -> None:
        assert _sanitise_tag_value("Ro\x00ck\x00") == "Rock"

    def test_clean_string_unchanged(self) -> None:
        assert _sanitise_tag_value("Jazz") == "Jazz"

    def test_empty_string(self) -> None:
        assert _sanitise_tag_value("") == ""

    def test_non_string_converted(self) -> None:
        assert _sanitise_tag_value(42) == "42"

    def test_object_with_failing_str_uses_repr(self) -> None:
        class BadStr:
            def __str__(self) -> str:
                raise ValueError("nope")

            def __repr__(self) -> str:
                return "<BadStr>"

        assert _sanitise_tag_value(BadStr()) == "<BadStr>"


# ---------------------------------------------------------------------------
# Supported extensions smoke test
# ---------------------------------------------------------------------------


class TestSupportedExtensions:
    """Verify all documented extensions are in SUPPORTED_EXTENSIONS."""

    @pytest.mark.parametrize("ext", [".flac", ".mp3", ".m4a", ".ogg", ".wav"])
    def test_extension_in_supported(self, ext: str) -> None:
        from backend.services.library_scan_service import SUPPORTED_EXTENSIONS

        assert ext in SUPPORTED_EXTENSIONS


# ---------------------------------------------------------------------------
# Generic fallback branch in read_tags
# ---------------------------------------------------------------------------


class TestExtractTagsGenericFallback:
    """Test the generic fallback when tag type is not ID3/Vorbis/WAV."""

    @patch("backend.services.library_scan_service.mutagen.File")
    def test_generic_fallback_returns_library_file(
        self, mock_file: MagicMock, tmp_path: Path
    ) -> None:
        """Unknown tag type should hit the generic fallback path."""
        fake_audio = MagicMock()
        fake_audio.tags = MagicMock()
        type(fake_audio.tags).__name__ = "UnknownTagType"
        fake_audio.info.length = 120.5
        fake_audio.info.bitrate = 128000
        mock_file.return_value = fake_audio

        path = tmp_path / "track.m4a"
        path.write_bytes(b"\x00" * 100)

        from backend.services.library_scan_service import read_tags

        result = read_tags(path)

        assert result.format == "aac"
        assert result.audio.duration_ms == 120500
        assert result.audio.track_title is None
        assert result.audio.recording_mbid is None

    @patch("backend.services.library_scan_service.mutagen.File")
    def test_id3_tag_type_fallback_dispatches_to_the_id3_extractor(
        self, mock_file: MagicMock, tmp_path: Path
    ) -> None:
        """An unlisted extension whose tag type names ID3 still gets ID3 fields."""

        class ID3Tags(dict):  # a real class so its __name__ names "ID3"
            pass

        fake_audio = MagicMock()
        fake_audio.tags = ID3Tags(TIT2=["Fallback Title"])
        fake_audio.info.length = 10.0
        fake_audio.info.bitrate = 96000
        mock_file.return_value = fake_audio

        path = tmp_path / "track.m4a"
        path.write_bytes(b"\x00" * 100)

        result = read_tags(path)

        assert result.audio.track_title == "Fallback Title"

    @patch("backend.services.library_scan_service.mutagen.File")
    def test_vorbis_tag_type_fallback_dispatches_to_the_vorbis_extractor(
        self, mock_file: MagicMock, tmp_path: Path
    ) -> None:
        """An unlisted extension whose tag type names VComment still gets Vorbis fields."""

        class VCommentDict(dict):  # a real class so its __name__ names "VComment"
            pass

        fake_audio = MagicMock()
        fake_audio.tags = VCommentDict(title=["Fallback Vorbis Title"])
        fake_audio.info.length = 10.0
        fake_audio.info.bitrate = 96000
        mock_file.return_value = fake_audio

        path = tmp_path / "track.m4a"
        path.write_bytes(b"\x00" * 100)

        result = read_tags(path)

        assert result.audio.track_title == "Fallback Vorbis Title"

    @patch("backend.services.library_scan_service.mutagen.File")
    def test_an_unidentifiable_file_raises_mutagen_error(
        self, mock_file: MagicMock, tmp_path: Path
    ) -> None:
        """mutagen.File returns None when it cannot determine the file's type."""
        mock_file.return_value = None
        path = tmp_path / "track.mp3"
        path.write_bytes(b"\x00" * 100)

        with pytest.raises(MutagenError):
            read_tags(path)


# ---------------------------------------------------------------------------
# Small tag-parse fallbacks: malformed values are dropped, not raised
# ---------------------------------------------------------------------------


class TestTagParseFallbacks:
    def test_parse_slash_int_returns_none_for_non_numeric_value(self) -> None:
        assert _parse_slash_int("not-a-number") is None

    def test_to_release_type_returns_none_for_an_unknown_value(self) -> None:
        assert _to_release_type("not-a-release-type") is None

    def test_to_release_status_returns_none_for_an_unknown_value(self) -> None:
        assert _to_release_status("not-a-release-status") is None

    def test_extract_audio_stream_metrics_returns_none_none_when_info_is_missing(self) -> None:
        fake_audio = MagicMock()
        fake_audio.info = None

        assert _extract_audio_stream_metrics(fake_audio) == (None, None)

    def test_extract_audio_stream_metrics_bitrate_is_bits_per_second_floor_divided_by_1000(
        self,
    ) -> None:
        """AUD-009 gate 2: kills the FloorDiv/NumberReplacer survivors on this line."""
        fake_audio = MagicMock()
        fake_audio.info.length = 10.0
        fake_audio.info.bitrate = 1_000_000

        _duration_ms, bitrate = _extract_audio_stream_metrics(fake_audio)

        assert bitrate == 1000


def test_extract_first_tag_value_uses_the_first_of_several_list_elements() -> None:
    """AUD-009 gate 2: every existing fixture's list tags have one element, so a
    survived mutant swapping index 0 for 1 went uncaught."""
    assert _extract_first_tag_value({"key": ["first", "second"]}, "key") == "first"


def test_disk_stat_is_frozen() -> None:
    """AUD-009 gate 2: kills the ReplaceTrueWithFalse survivor on frozen=True."""
    stat = DiskStat(size=1, mtime_ns=1)

    with pytest.raises(dataclasses.FrozenInstanceError):
        stat.size = 2  # type: ignore[misc]


# ---------------------------------------------------------------------------
# Non-MutagenError exception path in scan_directory
# ---------------------------------------------------------------------------


class TestScanDirectoryNonMutagenError:
    """Non-MutagenError exceptions during scan should create quarantine entries."""

    def test_non_mutagen_error_quarantines_file(self, tmp_path: Path) -> None:
        """A generic Exception during read_tags produces a quarantine entry."""
        audio_dir = tmp_path / "music"
        audio_dir.mkdir()
        bad_file = audio_dir / "problem.mp3"
        bad_file.write_bytes(b"\x00" * 10)

        with patch(
            "backend.services.library_scan_service.read_tags",
            side_effect=PermissionError("Access denied"),
        ):
            from backend.services.library_scan_service import scan_directory

            files, quarantine = scan_directory(audio_dir)

        assert len(files) == 0
        assert len(quarantine) == 1
        assert quarantine[0].file_path == str(bad_file)
        assert "PermissionError" in quarantine[0].error_message
        assert "Access denied" in quarantine[0].error_message

    def test_non_mutagen_error_calls_on_quarantine(self, tmp_path: Path) -> None:
        """on_quarantine callback fires for non-MutagenError exceptions too."""
        audio_dir = tmp_path / "music"
        audio_dir.mkdir()
        bad_file = audio_dir / "broken.ogg"
        bad_file.write_bytes(b"\x00" * 10)

        callback = MagicMock()

        with patch(
            "backend.services.library_scan_service.read_tags",
            side_effect=OSError("Disk read error"),
        ):
            from backend.services.library_scan_service import scan_directory

            scan_directory(audio_dir, on_quarantine=callback)

        callback.assert_called_once()
        entry = callback.call_args[0][0]
        assert "OSError" in entry.error_message


class TestReadTags:
    def test_scan_directory_still_quarantines_bad_files(self) -> None:
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        files, quarantine = scan_directory(AUDIO_DIR)
        assert len(files) == 4
        assert len(quarantine) == 1
        assert all(lf.file_size is not None for lf in files)

    def test_scan_directory_never_reads_audio_bytes(self) -> None:
        """None of the fixture files carries a FLAC with a stored MD5, so a scan
        that reads audio bytes at all (not just a whole file) is a regression.

        The previous version of this guard patched ``extract_tags``, a name
        removed by PR B (scans read tags only); with ``create=True`` it could
        never fail. ``_sha256_of_range`` is the primitive every audio-byte read
        goes through (see tests/services/test_read_tags_audio_hash.py and
        tests/integration/test_scan_then_backfill.py::test_a_rescan_hashes_no_audio_bytes,
        which guard the same call for FLACs and a real scanned library).
        """
        if not AUDIO_DIR.exists():
            pytest.skip("Audio fixtures directory not found")
        with patch(
            "backend.services.audio_hash._sha256_of_range",
            side_effect=AssertionError("scan_directory hashed audio bytes"),
        ):
            files, quarantine = scan_directory(AUDIO_DIR)

        assert (len(files), len(quarantine)) == (4, 1)
