from __future__ import annotations

from datetime import UTC, datetime

from backend.domain.system import UserSetting
from backend.repositories.user_settings import UserSettingRepository


class FakeUserSettingRepository(UserSettingRepository):
    """In-memory fake for :class:`UserSettingRepository`.

    Accepts an optional ``dict[str, str]`` for convenience so existing test
    fixtures that build settings as plain mappings do not require boilerplate.
    Internally all values are stored as :class:`UserSetting` instances.

    Intentional differences from :class:`PgUserSettingRepository`:
    - ``updated_at`` is generated by ``datetime.now(UTC)`` rather than the DB clock.
    - No transaction semantics; all writes are immediately visible.
    """

    def __init__(self, initial: dict[str, str] | None = None) -> None:
        now = datetime.now(UTC)
        self._data: dict[str, UserSetting] = {
            key: UserSetting(key=key, value=value, updated_at=now)
            for key, value in (initial or {}).items()
        }

    def get(self, key: str) -> UserSetting | None:
        return self._data.get(key)

    def upsert(self, setting: UserSetting) -> UserSetting:
        persisted = UserSetting(
            key=setting.key,
            value=setting.value,
            updated_at=datetime.now(UTC),
        )
        self._data[setting.key] = persisted
        return persisted

    def list_all(self) -> list[UserSetting]:
        return sorted(self._data.values(), key=lambda s: s.key)

